"""Constants for the AI RAG module."""

from __future__ import annotations

DEFAULT_PROVIDER = "openai"
DEFAULT_MODEL = "gpt-4.1"
DEFAULT_TEMPERATURE = 0.2
DEFAULT_MAX_TOKENS = 2048
DEFAULT_TOP_K = 5
DEFAULT_SCORE_THRESHOLD = 0.75
MAX_CONTEXT_DOCUMENTS = 10
MAX_CONTEXT_LENGTH = 16_000
