repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.21
    hooks:
      - id: ruff
        args:
          - --fix
        files: ^ai-config/

      - id: ruff-format
        files: ^ai-config/

  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        files: ^ai-config/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - ai-memory/src
        additional_dependencies:
          - pydantic
          - pydantic-settings
        files: ^ai-memory/