version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

    volumes:
      - ./backend:/app/backend

  postgres:

    image: postgres:17

    restart: always

    environment:

      POSTGRES_USER: support

      POSTGRES_PASSWORD: support

      POSTGRES_DB: support_db

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

  redis:

    image: redis:8

    ports:

      - "6379:6379"

volumes:

  postgres_data: